In [15]:
import tensorflow as tf
import numpy as np

In [9]:
d = tf.constant([7,8,9,10,11,12, 23, 22, 29, 1, 3,
                 5, 9,8, 7, 1, 31,12, 23, 22, 29, 1, 3, 5], 
                shape = [3, 2, 2, 2])
d_pad = tf.pad(d, [[1,0], [1, 0], [0,0], [3,1]], "CONSTANT")


In [10]:
with tf.Session() as sess:
    print(d.eval())
    print(d_pad.eval())

[[[[ 7  8]
   [ 9 10]]

  [[11 12]
   [23 22]]]


 [[[29  1]
   [ 3  5]]

  [[ 9  8]
   [ 7  1]]]


 [[[31 12]
   [23 22]]

  [[29  1]
   [ 3  5]]]]
[[[[ 0  0  0  0  0  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0  0  0  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0  0  0  0]
   [ 0  0  0  0  0  0]]]


 [[[ 0  0  0  0  0  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0  7  8  0]
   [ 0  0  0  9 10  0]]

  [[ 0  0  0 11 12  0]
   [ 0  0  0 23 22  0]]]


 [[[ 0  0  0  0  0  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0 29  1  0]
   [ 0  0  0  3  5  0]]

  [[ 0  0  0  9  8  0]
   [ 0  0  0  7  1  0]]]


 [[[ 0  0  0  0  0  0]
   [ 0  0  0  0  0  0]]

  [[ 0  0  0 31 12  0]
   [ 0  0  0 23 22  0]]

  [[ 0  0  0 29  1  0]
   [ 0  0  0  3  5  0]]]]


In [18]:
a = [1, 2, 4, 45]
b = [7, 9, 6, 3, 2, 3]
for i, j in zip(a, b):
    print (i, j)

(1, 7)
(2, 9)
(4, 6)
(45, 3)
